name: Generate Weekly Log

on:
  schedule:
    - cron: '0 15 * * 3'  # Setiap hari Rabu jam 22:00 WIB (15:00 UTC)
  workflow_dispatch:

jobs:
  generate-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Git config
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"

    # Step untuk memastikan folder weekly-log ada
    - name: Ensure weekly-log directory exists
      run: mkdir -p weekly-log

    - name: Generate weekly log
      run: |
        WEEK_NUMBER=$(date +'%V')
        FILE_PATH="weekly-log/week-${WEEK_NUMBER}.md"
        echo "Week ${WEEK_NUMBER} Log" > "$FILE_PATH"
        echo "Generated log for week ${WEEK_NUMBER}" >> "$FILE_PATH"
        git add "$FILE_PATH"
        git commit -m "Add weekly log for week ${WEEK_NUMBER}"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

    - name: Send notification email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "✅ Weekly Log Week-${{ github.run_number }} Created"
        body: |
          Weekly log untuk minggu ini telah otomatis dibuat.
          Silakan cek file terbaru di folder `weekly-log/` di repositori kamu.

          Keep pushing your Data Science journey! 💪📊
        to: ${{ secrets.EMAIL_RECEIVER }}
        from: ${{ secrets.EMAIL_USERNAME }}
